### PR TITLE
Sunday Structure setup

### PR DESCRIPTION
**Pull request by tatsvc**
Per https://github.com/openstreetmap/stateofthemap-2016/issues/34 @katydecorah set up a structure for the Sunday Program Schedule. @RobJN can you go ahead and start adding the markdown files to this PR! Please let me know if anything breaks!

---

Posts for Sunday have two new variables:
- capacity
- track

The `track` number keeps the 6 talks in each slot in order.

For tags, the first slot on Sunday is `slot31`. The next is `slot32` and then `slot33` and finally `slot33`.

I added 6 example posts for testing - that we should remove before we merge!

image

---

### CODE REVIEW

**Comment by RobJN** [comment]
Thank you. This looks great. Will get on to the markdown files later this
week (on vacation at the moment).

**Comment by RobJN** [comment]
Program markdown files added. Now ready to be merged.

**Comment by tatsvc** [comment]
@RobJN I'm seeing some small issues here with the design, hoping to fix it tomorrow on the plane to Seattle for SOTMUS!

**Comment by tatsvc** [comment]
@RobJN I pushed some fixes. I you feel good about it, we can merge!

**Pull request merged**
