### PR TITLE
Adding accommodation details

### PR DESCRIPTION
**Pull request by tatsvc**
Per https://github.com/osmbe/sotm2016/issues/27 adding the accommodation details to the venue page:

screenshot-localhost 4000 2016-02-26 11-15-22

cc. @mikelmaron for review

### CODE REVIEW

**Comment by tatsvc** [comment]
image

**Comment by mikelmaron** [comment]
thanks @tatsvc. looks good. @RobJN can you review and merge?

**Comment by tatsvc** [comment]
No merging yet please :blush: I'm still working on the branch!

**Comment by tatsvc** [comment]
Added maps.me, but we need more sponsors :weary: 

image

**Comment by tatsvc** [comment]
image

**Comment by tatsvc** [comment]
Going to merge these changes! @RobJN can you cut new tickets if you have feedback? Just want to get this out of the door before the weekend!

**Comment by RobJN** [comment]
Thanks both :+1:
I don't see the new sponsors section live on the site but assume this was held back until we have a few more sponsors (?)

**Comment by tatsvc** [comment]
> I don't see the new sponsors section live on the site but assume this was held back until we have a few more sponsors (?)

Exactly :blush: but I have it ready to go for once we do have a few more!

**Pull request merged**
